# Generated by Django 4.1.3 on 2023-02-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appAsso", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Stock",
        ),
    ]
