# Generated by Django 4.1.3 on 2023-02-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appAsso", "0002_rename_product_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="basketP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nomProduit", models.CharField(max_length=45)),
                ("prix", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="boxeP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nomProduit", models.CharField(max_length=45)),
                ("prix", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="footP",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nomProduit", models.CharField(max_length=45)),
                ("prix", models.FloatField(default=0.0)),
            ],
        ),
    ]
