# Generated by Django 4.1.3 on 2023-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appAsso", "0003_basketp_boxep_footp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxep",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="footp",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
