# Generated by Django 4.1.3 on 2023-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appAsso", "0004_alter_boxep_id_alter_footp_id_alter_stock_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="boxep",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="footp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
