# Generated by Django 4.1.6 on 2023-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appAsso", "0005_alter_basketp_id_alter_boxep_id_alter_footp_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="img",
            field=models.ImageField(blank=True, upload_to="imgs"),
        ),
        migrations.AddField(
            model_name="stock",
            name="quantite",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
