# Generated by Django 4.1.3 on 2023-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAsso', '0008_alter_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantite',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
